name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: |
          npm install
#          npm install -D @percy/script
#
#      - name: Visual Tests
#        uses: percy/exec-action@v0.1.1
#        with:
#          command: "node tests/visual.js"
#        env:
#          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Cross-Browser Tests
        run: "node --experimental-modules tests/snapshots.js"
        env:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          branchName: ${GITHUB_REF##*/}
          browserstackUsername: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstackAutomateKey: ${{ secrets.BROWSERSTACK_AUTOMATE_KEY }}
